### ISSUE TITLE
Contribution rules

### ISSUE THREAD

**Issue by csuire01** [LP-Dev-Cloud/kb2021#13]
We will discuss this issue in class. 

As you can see, the first contributions do not follow any rules, the commit messages are diverse, the branch names are not fixed, the section titles are not uniform, etc. 

We need to collectively decide on a number of rules that we will post in a [contributing](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file.

**Comment by EstebanChacon** [comment]
Rule for the commits :
Set some [gitmoji](https://gitmoji.dev/ ) to add a the start of the commits message to simplify the comprehension for everyone
