### ISSUE TITLE
Problème pour build le book

### ISSUE THREAD

**Issue by cbellec** [LP-Dev-Cloud/kb2021#31]
Après quelques test, je pense qu'il y a un problème pour build notamment avec le fichier  "/home/tpuser/Documents/projets/kb2021/kb2021/harmonisation_prog/js"

![bug](https://user-images.githubusercontent.com/89917934/140944376-b3b088d1-2b3e-45fd-bd8d-4a12f521ed23.png)

**Comment by p0lycarpio** [comment]
Salut Corentin,
Je pense qu'il te manque le noyau Javascript pour que Jupyter build le book.
Essaye de l'installer en suivant [cette procédure](https://lp-dev-cloud.github.io/kb2021/harmonisation_prog/intro_js.html) (installation de Node + noyau JS)
